version: "3.9"

services:
  db:
    image: mysql:5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=django
      - MYSQL_DATABASE=django
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "5555:8000"
    depends_on:
      - db